server:
  port: 30000
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board_study?characterEncoding=UTF-8
    username: root
    password: akfldk1elql
  servlet:
    multipart:
      location: C:\\dev\\Tool\\uploadFiles
      max-file-size: 30MB
      max-request-size: 30MB
mybatis:
  type-aliases-package: com.study.board.vo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
logging:
  level:
    root: debug
  charset:
    console: UTF-8