server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board_study?characterEncoding=UTF-8
    username: root
    password: akfldk1elql
mybatis:
  type-aliases-package: com.study.board.vo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml